name: node-version

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      
      - run: node -v
      - run: npm -v
      
